
server:
  port: 8081
# 应用名称：client
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #数据库url
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    # 数据库访问账户
    username: root
    # 数据库访问密码
    password: 123456
  application:
    name: client
# 注册到我们本地的eureka注册中心，端口是8080
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8080/eureka/
