server:
  port: 8087
# 应用名称：client
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #数据库url
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    # 数据库访问账户
    username: root
    # 数据库访问密码
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka/
  instance:
    prefer-ip-address: true
ribbon.eureka.enable: true
